# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/auth_protos.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/auth_protos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/auth_protos.proto\x12\x04\x61uth\"!\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"<\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\"0\n\rSignUpRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"*\n\x0eSignUpResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.auth.User\",\n\x13RefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\",\n\x14RefreshTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t2\xb4\x01\n\x04\x41uth\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12\x33\n\x06SignUp\x12\x13.auth.SignUpRequest\x1a\x14.auth.SignUpResponse\x12\x45\n\x0cRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x1a.auth.RefreshTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.auth_protos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=34
  _globals['_USER']._serialized_end=67
  _globals['_LOGINREQUEST']._serialized_start=69
  _globals['_LOGINREQUEST']._serialized_end=116
  _globals['_LOGINRESPONSE']._serialized_start=118
  _globals['_LOGINRESPONSE']._serialized_end=178
  _globals['_SIGNUPREQUEST']._serialized_start=180
  _globals['_SIGNUPREQUEST']._serialized_end=228
  _globals['_SIGNUPRESPONSE']._serialized_start=230
  _globals['_SIGNUPRESPONSE']._serialized_end=272
  _globals['_REFRESHTOKENREQUEST']._serialized_start=274
  _globals['_REFRESHTOKENREQUEST']._serialized_end=318
  _globals['_REFRESHTOKENRESPONSE']._serialized_start=320
  _globals['_REFRESHTOKENRESPONSE']._serialized_end=364
  _globals['_AUTH']._serialized_start=367
  _globals['_AUTH']._serialized_end=547
# @@protoc_insertion_point(module_scope)
